Proyecto/Pagina/Models/ImageViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pagina.Models
{
    public class ImageViewModels
    {
        public string Id { get; set; }
        public string Photo { get; set; }
    }
}

Proyecto/Pagina/Controllers/GemasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pagina.Models;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class GemasController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Gemas
        public ActionResult Index()
        {
            return View(db.Gemas.ToList());
        }

        // GET: Gemas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gema gema = db.Gemas.Find(id);
            if (gema == null)
            {
                return HttpNotFound();
            }
            return View(gema);
        }

        [HttpPost]
        public ActionResult Create(Gema gema)
        {
            if (ModelState.IsValid)
            {
                db.Gemas.Add(gema);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gema);
        }

        [HttpPost]
        public ActionResult Edit(Gema gema)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gema).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gema);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(IEnumerable<int> ID)
        {
            var gemas = db.Gemas.ToList();

            foreach (var item in gemas)
            {
                foreach (var id in ID)
                {
                    if (id == item.ID)
                    {
                        var borrargema = db.Gemas.FirstOrDefault(p => p.ID == id);
                        db.Gemas.Remove(borrargema);
                    }
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");          
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto/Pagina/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Pagina.Models;

namespace Pagina.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Order
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var producto = db.Productos.Include(p => p.Gema).Include(p => p.Tipo).FirstOrDefault(p => p.ID == id);

            if (producto == null)
            {
                return HttpNotFound();
            }

            return View(producto);
        }

        [HttpPost]
        public ActionResult Encargo(int? idp, HttpPostedFileBase amount)
        {
            var userid = User.Identity.GetUserId();
            var producto = db.Productos.Include(p => p.Gema).Include(p => p.Tipo).FirstOrDefault(p => p.ID == idp);
            Pedido pedido = new Pedido();
            pedido.ProductoID = producto.ID;
            pedido.ClienteID = userid;
            pedido.Total = producto.Precio;
            pedido.Estado = "En carro";

            db.Pedidos.Add(pedido);
            db.SaveChanges();

            return RedirectToAction("Index", new { id = idp});
        }

        public ActionResult BorrarEncargo(int idpedido)
        {
            Pedido pedido = db.Pedidos.Find(idpedido);
            db.Pedidos.Remove(pedido);
            db.SaveChanges();
            return RedirectToAction("ShoppingCart");
        }

        public ActionResult ShoppingCart(OrderViewModels OVM)
        {
            var ID = User.Identity.GetUserId();
            var user = db.Users.Find(ID);
            var pedidos = db.Pedidos.Include(p => p.Producto).Where(p => p.ClienteID == ID).Where(p => p.Estado == "En carro");

            OVM.Usuario = user;
            OVM.Pedidos = pedidos.ToList();

            return View(OVM);
        }

        public ActionResult Payment()
        {
            var ID = User.Identity.GetUserId();
            var user = db.Users.Find(ID);

            if (user.PaymentSave == true)
            {
                var pedidos = db.Pedidos.Include(p => p.Producto).Where(p => p.ClienteID == ID).Where(p => p.Estado == "En carro").ToList();

                db.SaveChanges();
                return RedirectToAction("PaymentComplete");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Payment(PaymentViewModels PVM)
        {
            var ID = User.Identity.GetUserId();
            var user = db.Users.Find(ID);
            var pedidos = db.Pedidos.Include(p => p.Producto).Where(p => p.ClienteID == ID).Where(p => p.Estado == "En carro").ToList();

            user.Address = PVM.Address;
            user.Country = PVM.Country;
            user.State = PVM.State;
            user.ZipCode = PVM.Zip;
            user.PaymentName = PVM.PaymentName;
            user.PaymentNumber = PVM.PaymentNumber;
            user.PaymentExpDate = PVM.PaymentExpDate;
            user.PaymentCCV = PVM.PaymentCCV;
            user.PaymentMethod = PVM.PaymentMethod;
            user.PaymentSave = PVM.PaymentSave;

            db.SaveChanges();

            return RedirectToAction("PaymentComplete");
        }

        public ActionResult PaymentComplete(OrderViewModels OVM)
        {          
            var ID = User.Identity.GetUserId();
            var user = db.Users.Find(ID);
            var pedidos = db.Pedidos.Include(p => p.Producto).Where(p => p.ClienteID == ID).Where(p => p.Estado == "En carro").ToList();

            OVM.Usuario = user;
            OVM.Pedidos = pedidos.ToList();

            foreach (var item in pedidos)
            {
                Pedido pedido = db.Pedidos.Find(item.ID);
                pedido.Estado = "Comprado";
            }

            db.SaveChanges();

            return View(OVM);
        }
    }
}

Proyecto/Pagina/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Pagina.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolesController : Controller
    {
        
        readonly ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(UserViewModel UVM)
        {
            var users = (from user in db.Users
                                  from userRole in user.Roles
                                  join role in db.Roles on userRole.RoleId equals
                                  role.Id
                                  select new UserViewModel()
                                  {
                                      ID = user.Id,
                                      Username = user.UserName,
                                      Email = user.Email,
                                      Role = role.Name
                                  }).ToList();

            return View(users);
        }
        
        public ActionResult AddRoles(string id)
        {
            var user = db.Users.Find(id);
            return View(user);
        }

        [HttpPost]
        public ActionResult AddRoles(UserViewModel UVM)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userRol = userManager.GetRoles(UVM.ID);

            if (userRol.Count > 0)
            {
                userManager.RemoveFromRoles(UVM.ID,userRol.ToArray());
                userManager.AddToRole(UVM.ID,UVM.Role);
            }
            else
            {
                userManager.AddToRole(UVM.ID, UVM.Role);
            }

            return RedirectToAction("Index");
        }

    }
}

Proyecto/Pagina/Controllers/SharedController.cs
using Microsoft.AspNet.Identity;
using Pagina.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina.Controllers
{
    public class SharedController : Controller
    {
        readonly ApplicationDbContext db = new ApplicationDbContext();
        // GET: LoginPartial
        [ChildActionOnly]
        public ActionResult _LoginPartial()
        {
            var ID = User.Identity.GetUserId();
            var user = db.Users.Find(ID);

            return PartialView(user);
        }
    }
}

Proyecto/Pagina/Views/Shared/_Image.cshtml
@model Pagina.Models.ApplicationUser
<img src="" />

Proyecto/Pagina/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - CrystalPlus</title>
    <link rel="icon" type="image/png" href="~/Upload/Assets/crystalplus.ico" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="~/Content/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav sidebar sidebar-dark sidebar-color accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
                <div class="sidebar-brand-icon rotate-n-15" style="color: black;">
                    <i class="fas fa-gem"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Crystal <b>+</b></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <div class="sidebar-heading">
                Menu
            </div>
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Articulos")">
                    <i class="fas fa-ring"></i>
                    <span>Articulos</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShoppingCart","Order")">
                    <i class="fas fa-shopping-cart"></i>
                    <span>Carrito</span>
                </a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
        <hr class="sidebar-divider">

                        <div class="sidebar-heading">
                            Herramientas
                        </div>


                                        <li class="nav-item">
                                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                                               aria-expanded="true" aria-controls="collapseTwo">
                                                <i class="fas fa-fw fa-cog"></i>
                                                <span>CRUD</span>
                                            </a>
                                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                                                <div class="bg-white py-2 collapse-inner rounded">
                                                    <h6 class="collapse-header">Menu:</h6>
                                                    <a class="collapse-item" href='@Url.Action("Index", "Productoes")'>Productos</a>
                                                    <a class="collapse-item" href="@Url.Action("Index", "Pedidoes")">Pedidos</a>
                                                    <a class="collapse-item" href="@Url.Action("Index", "Gemas")">Gemas</a>
                                                    <a class="collapse-item" href="@Url.Action("Index", "Tipoes")">Tipos</a>
                                                </div>
                                            </div>
                                        </li>
            }


            @if (User.IsInRole("Administrador"))
            {
        <li class="nav-item">
            <a class="nav-link" aria-expanded="true" href="@Url.Action("Index", "Roles")">
                <i class="fas fa-fw fa-address-book"></i>
                <span>Roles</span>
            </a>
        </li>}
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Información
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                   aria-controls="collapsePages">
                    <i class="far fa-gem"></i>
                    <span>Crystal+</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <h6 class="collapse-header">Menu</h6>
                            <a class="collapse-item" href="@Url.Action("History","Profile")">Historial de compras</a>
                            <a class="collapse-item" href="@Url.Action("PaymentMethod","Profile")">Metodo de pago</a>
                            <div class="collapse-divider"></div>
                        }
                        <h6 class="collapse-header">Contacto:</h6>
                        <a class="collapse-item" href="@Url.Action("About","Home")">Sobre nosotros</a>
                        <a class="collapse-item" href="@Url.Action("Contact","Home")">Información de contacto</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                
                    <!-- Nav Item - User Information -->
                    @Html.Action("_LoginPartial", "Shared")


                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Francisco Javier Topete Zambrano</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="~/Scripts/jquery-3.5.1.slim.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.easing.min.js" type="text/javascript"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity=
        "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
    <!--<script src="~/Scripts/bootstrap.js" type="text/javascript"></script>-->
    <script src="~/Scripts/sb-admin-2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/mdb.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        new WOW().init();</script>
    <script type="text/javascript" src="~/Scripts/crud.js"></script>
</body>
</html>