Proyecto/Pagina/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CrudController : Controller
    {
        // GET: Crud
        public ActionResult Index()
        {
            return View();
        }
    }
}

Proyecto/Pagina/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Proyecto/Pagina/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Pagina.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolesController : Controller
    {
        
        readonly ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(UserViewModel UVM)
        {
            var users = (from user in db.Users
                                  from userRole in user.Roles
                                  join role in db.Roles on userRole.RoleId equals
                                  role.Id
                                  select new UserViewModel()
                                  {
                                      ID = user.Id,
                                      Username = user.UserName,
                                      Email = user.Email,
                                      Role = role.Name
                                  }).ToList();

            return View(users);
        }
        
        public ActionResult AddRoles(string id)
        {
            var user = db.Users.Find(id);
            return View(user);
        }

        [HttpPost]
        public ActionResult AddRoles(UserViewModel UVM)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userRol = userManager.GetRoles(UVM.ID);

            if (userRol.Count > 0)
            {
                userManager.RemoveFromRoles(UVM.ID,userRol.ToArray());
                userManager.AddToRole(UVM.ID,UVM.Role);
            }
            else
            {
                userManager.AddToRole(UVM.ID, UVM.Role);
            }

            return RedirectToAction("Index");
        }

    }
}

Proyecto/Pagina/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre nosotros";
}

<link href="~/Content/aboutus.css" rel="stylesheet">

<br /><br /><br />

<div class="container-fluid">
    <hr />
        <h2 class="title-about-us">Sobre Crytal+</h2>
    <hr />
    <br /><br />

    <div class="row no-gutters">
        <div class="col-lg-6">
            <img class="image-about-us" src="https://www.pngkey.com/png/detail/19-193530_gold-jewellery-model-png.png" />
        </div>
        <div class="col-lg-5 ml-n2" style="background-color: darkslateblue;">
            <h3 class="desct-about-us">¿Quienes somos?</h3>
            <br />
            <p class="desc-about-us">
                Crystal+ siempre ha hecho gala de su gran corazón, estableciendo la generosidad y la entrega por los demás como sus valores fundamentales.<br /> La colección Happy Hearts, una combinación perfecta entre el corazón talismán de Crystal+ y sus emblemáticos diamantes móviles, une a todas las mujeres de gran corazón del mundo.<br /> Las creaciones Happy Diamonds son tan audaces como divertidas, con sus emblemáticos diamantes móviles, que se mueven y giran suavemente entre dos cristales de zafiro, para simbolizar la alegría de vivir y una auténtica libertad de espíritu.
            </p>
        </div>
    </div>
</div>

Proyecto/Pagina/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2 class="titulo subtitulo t-crud">@ViewBag.Title.</h2>

<address class="detalles">
    Zona Rio<br />
    Local 123, Zona Rio<br />
    <abbr title="Phone">P:</abbr>
    123.456.7890
</address>

<address class="detalles">
    <strong>Soporte:</strong>   <a href="mailto:Support@example.com">Soporte@ejemplo.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@ejemplo.com</a>
</address>

Proyecto/Pagina/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Lo mejor en Joyeria!";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Crystal+</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img width="100" height="100" src="~/Upload/Assets/logo.png" /></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="@Url.Action("About","Home")">Sobre Nosotros</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="@Url.Action("Index","Crud")">CRUD</a></li>
                    }

                    @if (User.IsInRole("Administrador"))
                    {
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="@Url.Action("Index","Roles")">Roles</a></li>

                    }
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Bienvenido a Crystal+</h1>
                    <hr class="divider my-4" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 font-weight-light mb-5">Donde tenemos la mejor selección de joyeria</p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="@Url.Action("Index","Articulos")">Mirala ya</a>
                </div>
            </div>
        </div>
    </header>
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Francisco Javier Topete Zambrano</div></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Scripts/scripts.js"></script>
</body>
</html>