Proyecto/Pagina/Controllers/TipoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pagina.Models;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class TipoesController : Controller
    {
        
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Tipoes
        public ActionResult Index()
        {
            return View(db.Tipos.ToList());
        }

        // GET: Tipoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo tipo = db.Tipos.Find(id);
            if (tipo == null)
            {
                return HttpNotFound();
            }
            return View(tipo);
        }

        // GET: Tipoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tipoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "ID,Nombre")] Tipo tipo)
        {
            if (ModelState.IsValid)
            {
                db.Tipos.Add(tipo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipo);
        }

        [HttpPost]
        public ActionResult Edit(Tipo tipo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipo);
        }

       
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(IEnumerable<int> ID)
        {
            var tipos = db.Tipos.ToList();

            foreach (var item in tipos)
            {
                foreach (var id in ID)
                {
                    if (id == item.ID)
                    {
                        var borrartipo = db.Tipos.FirstOrDefault(p => p.ID == id);
                        db.Tipos.Remove(borrartipo);
                    }
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto/Pagina/Views/Tipoes/Create.cshtml
@model Pagina.Models.Tipo

@{
    ViewBag.Title = "Crear";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="boton-crear" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Pagina/Views/Tipoes/Delete.cshtml
@model Pagina.Models.Tipo

@{
    ViewBag.Title = "Borrar Tipo";
}
<h3 class="titulo subtitulo" style="color: black;">Seguro que quieres borrar esto?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="boton-crear" />
        </div>
    }
</div>

Proyecto/Pagina/Views/Tipoes/Details.cshtml
@model Pagina.Models.Tipo

@{
    ViewBag.Title = "Detalles";
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar!", "Edit", new { id = Model.ID }, new { @class = "boton-tabla" })
</p>

Proyecto/Pagina/Views/Tipoes/Edit.cshtml
@model Pagina.Models.Tipo

@{
    ViewBag.Title = "Editar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="boton-crear" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Pagina/Views/Tipoes/Index.cshtml
@model IEnumerable<Pagina.Models.Tipo>

@{
    ViewBag.Title = "CRUD";
}


<link href="~/Content/crudStyles.css" rel="stylesheet">

<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2><b>Tipos</b></h2>
                    </div>
                    <div class="col-sm-6">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a href="#createTiposModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i><span></span></a>
                            <a href="#deleteTiposModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i><span></span></a>
                        }
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <span class="custom-checkbox">
                                <input type="checkbox" id="selectAll">
                                <label for="selectAll"></label>
                            </span>
                        </th>
                        <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int contador = 0;
                    }

                    @foreach (var item in Model)
                    {
                        var modaledit = "#editTiposModal" + contador.ToString();
                        var checkbox = "checkbox" + contador.ToString();
                        <tr>
                            <td>
                                <span class="custom-checkbox">
                                    <input type="checkbox" id="@checkbox" value="@item.ID" name="ID" form="delete">
                                    <label for="@checkbox"></label>
                                </span>
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                            <td>
                                <a href="@modaledit" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i></a>
                            </td>
                        </tr>

                        contador++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@{ contador = 0;}

@foreach (var item in Model)
{
    var modaledit = "editTiposModal" + contador.ToString();

    <div id="@modaledit" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" action="@Url.Action("Edit","Tipoes")" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <div class="modal-header">
                        <h4 class="modal-title">Editar Tipo (#@item.ID)</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="ID" value="@item.ID" />
                        <div class="form-group">
                            <label>@Html.DisplayNameFor(model => model.Nombre)</label>
                            <input type="text" name="Nombre" class="form-control" value="@item.Nombre">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                        <input type="submit" class="btn btn-info" value="Aplicar">
                    </div>
                </form>
            </div>
        </div>
    </div>

    contador++;
}

<div id="createTiposModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="@Url.Action("Create","Tipoes")" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title">Crear Tipo</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Nombre)</label>
                        <input type="text" name="Nombre" class="form-control" placeholder="Nombre">
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-info" value="Crear">
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Modal HTML -->
<div id="deleteTiposModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="delete" method="post" action="@Url.Action("Delete","Tipoes")" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title">Borrar Gema(s)</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Seguro que quieres borrar los productos seleccionados?</p>
                    <p class="text-warning"><small>Esto no se puede deshacer.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-danger" value="Borrar">
                </div>
            </form>
        </div>
    </div>
</div>