Proyecto/Pagina/Controllers/PedidoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pagina.Models;
using System.Collections.ObjectModel;

namespace Pagina.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PedidoesController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Pedidoes
        public ActionResult Index(PedidosViewModel PEVM)
        {
            var usuarios = db.Users.ToList();
            var pedidos = db.Pedidos.Include(p => p.Producto).ToList();
            var productos = db.Productos.ToList();       
            PEVM.Productos = productos;
            PEVM.Pedidos = pedidos;
            PEVM.Clientes = usuarios;
            return View(PEVM);
        }

        // GET: Pedidoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pedido = db.Pedidos.Include(p => p.Producto).Include(p => p.Cliente).FirstOrDefault(p => p.ID == id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedidoes/Create
        public ActionResult Create()
        {
            ViewBag.ProductoID = new SelectList(db.Productos, "ID", "Nombre");
            return View();
        }

        // POST: Pedidoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedido);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductoID = new SelectList(db.Productos, "ID", "Nombre", pedido.ProductoID);
            return View(pedido);
        }

        [HttpPost]
        public ActionResult Edit(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedido).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductoID = new SelectList(db.Productos, "ID", "Nombre", pedido.ProductoID);
            return View(pedido);
        }


        // POST: Pedidoes/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(IEnumerable<int> ID)
        {
            var pedidos = db.Pedidos.ToList();

            foreach (var item in pedidos)
            {
                foreach (var id in ID)
                {
                    if (id == item.ID)
                    {
                        var borrarpedido = db.Pedidos.FirstOrDefault(p => p.ID == id);
                        db.Pedidos.Remove(borrarpedido);
                    }
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto/Pagina/Views/Pedidoes/Create.cshtml
@model Pagina.Models.Pedido

@{
    ViewBag.Title = "Crear";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductoID, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="boton-crear" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Pagina/Views/Pedidoes/Delete.cshtml
@model Pagina.Models.Pedido

@{
    ViewBag.Title = "Borrar Pedido";
}

<h3 class="titulo subtitulo" style="color: black;">Seguro que quieres borrar esto?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producto.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="boton-crear" />
        </div>
    }
</div>

Proyecto/Pagina/Views/Pedidoes/Details.cshtml
@model Pagina.Models.Pedido

@{
    ViewBag.Title = "Detalles";
}

<link href="~/Content/details.css" rel="stylesheet">

<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        <b>Pedido #@Html.DisplayFor(model => model.ID)</b>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="~/Upload/Productoes/@Model.Producto.Imagen" alt="">
        </div>

        <div class="col-md-4">           
            <h3 class="my-3"><b>Detalles</b></h3>
            <ul>
                <li><b>@Html.DisplayNameFor(model => model.Producto.Nombre):</b> @Html.DisplayFor(model => model.Producto.Nombre)</li>
                <li><b>Cliente:</b> @Html.DisplayFor(model => model.Cliente.UserName)</li>
                <li><b>@Html.DisplayNameFor(model => model.Total):</b> $@Html.DisplayFor(model => model.Total)</li>
                <li><b>@Html.DisplayNameFor(model => model.Estado):</b> @Model.Estado</li>
            </ul>
        </div>
    </div>
</div>

Proyecto/Pagina/Views/Pedidoes/Edit.cshtml
@model Pagina.Models.Pedido

@{
    ViewBag.Title = "Editar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductoID, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="boton-crear" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Pagina/Views/Pedidoes/Index.cshtml
@model Pagina.Models.PedidosViewModel

@{
    ViewBag.Title = "CRUD";
}


<link href="~/Content/crudStyles.css" rel="stylesheet">
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2><b>Pedidos</b></h2>
                    </div>
                    <div class="col-sm-6">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a href="#createPedidosModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i><span></span></a>
                            <a href="#deletePedidosModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i><span></span></a>
                        }
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <span class="custom-checkbox">
                                <input type="checkbox" id="selectAll">
                                <label for="selectAll"></label>
                            </span>
                        </th>
                        <th>@Html.DisplayNameFor(model => model.Pedido.Producto.Nombre)</th>
                        <th>@Html.DisplayNameFor(model => model.Pedido.Cliente.UserName)</th>
                        <th>@Html.DisplayNameFor(model => model.Pedido.Total)</th>
                        <th>@Html.DisplayNameFor(model => model.Pedido.Estado)</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int contador = 0;
                    }

                    @foreach (var item in Model.Pedidos)
                    {
                        var modaledit = "#editPedidosModal" + contador.ToString();
                        var checkbox = "checkbox" + contador.ToString();

                        <tr>
                            <td>
                                <span class="custom-checkbox">
                                    <input type="checkbox" id="@checkbox" value="@item.ID" name="ID" form="delete">
                                    <label for="@checkbox"></label>
                                </span>
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.Producto.Nombre)</td>
                            <td>@Html.DisplayFor(modelItem => item.Cliente.UserName)</td>
                            <td>@Html.DisplayFor(modelItem => item.Total)</td>
                            <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                            <td>
                                <a href="@modaledit" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i></a>
                                <a href="@Url.Action("Details", "Pedidoes", new { id = item.ID })" class="delete"><i class="material-icons" data-toggle="tooltip" title="Detalles">&#xf1c3;</i></a>
                            </td>
                        </tr>

                        contador++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@{ contador = 0;}

@foreach (var item in Model.Pedidos)
{
    var modaledit = "editPedidosModal" + contador.ToString();

    <div id="@modaledit" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" action="@Url.Action("Edit","Pedidoes")" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <div class="modal-header">
                        <h4 class="modal-title">Editar Pedido (#@item.ID)</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="ID" value="@item.ID" />
                        <div class="form-group">
                            <label>@Html.DisplayNameFor(model => model.Pedido.Producto.Nombre)</label>
                            <select name="ProductoID" class="form-control">
                                @foreach (var producto in Model.Productos)
                                {
                                    if (producto.ID == item.Producto.ID)
                                    {
                                        <option value="@producto.ID" selected>@producto.Nombre</option>
                                    }
                                    else
                                    {
                                        <option value="@producto.ID">@producto.Nombre</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>@Html.DisplayNameFor(model => model.Pedido.Cliente.UserName)</label>
                            <select name="ClienteID" class="form-control">
                                @foreach (var comprador in Model.Clientes)
                                {
                                    if (comprador.Id == item.ClienteID)
                                    {
                                        <option value="@comprador.Id" selected>@comprador.UserName</option>
                                    }
                                    else
                                    {
                                        <option value="@comprador.Id">@comprador.UserName</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>@Html.DisplayNameFor(model => model.Pedido.Total)</label>
                            <input type="number" name="Total" class="form-control" value="@item.Total" required />
                        </div>
                        <div class="form-group">
                            <label>@Html.DisplayNameFor(model => model.Pedido.Estado)</label>
                            <select name="Estado" class="form-control">
                                <option value="En carro" selected>En carro</option>
                                <option value="Comprado">Comprado</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                        <input type="submit" class="btn btn-info" value="Aplicar">
                    </div>
                </form>
            </div>
        </div>
    </div>

    contador++;
}

<div id="createPedidosModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="@Url.Action("Create","Pedidoes")" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title">Crear Pedido</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Pedido.Producto.Nombre)</label>
                        <select name="ProductoID" class="form-control">
                            @foreach (var producto in Model.Productos)
                            {
                                <option value="@producto.ID">@producto.Nombre</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Pedido.Cliente.UserName)</label>
                        <select name="ClienteID" class="form-control">
                            @foreach (var cliente in Model.Clientes)
                            {
                                <option value="@cliente.Id">@cliente.UserName</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Pedido.Total)</label>
                        <input type="number" name="Total" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Pedido.Total)</label>
                        <select name="Estado" class="form-control">
                            <option value="En carro">En carro</option>
                            <option value="Comprado">Comprado</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-info" value="Crear">
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Modal HTML -->
<div id="deletePedidosModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="delete" method="post" action="@Url.Action("Delete","Pedidoes")" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title">Borrar Producto(s)</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Seguro que quieres borrar los productos seleccionados?</p>
                    <p class="text-warning"><small>Esto no se puede deshacer.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-danger" value="Borrar">
                </div>
            </form>
        </div>
    </div>
</div>